[project]
name = "chessboard-car"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "scipy>=1.16.1",
    "uvicorn>=0.35.0",
]
